# Generated by Django 3.2.6 on 2021-09-04 18:25

from django.db import migrations, models
import identity.custom_validators.user


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_auto_20210904_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=11, unique=True, validators=[identity.custom_validators.user.MobileValidator], verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='technology',
            field=models.CharField(max_length=8, unique=True, validators=[identity.custom_validators.user.TechnologyValidator], verbose_name='员工编号'),
        ),
    ]
