# Generated by Django 3.2.6 on 2021-08-17 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cal_ACT_HYCB',
            new_name='calu_ACT_HYCB',
        ),
    ]
