# Generated by Django 3.2.6 on 2021-08-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0002_rename_cal_act_hycb_calu_act_hycb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dime_bd_materialgroup',
            name='parse_time',
            field=models.DateTimeField(db_column='爬取时间'),
        ),
        migrations.AlterField(
            model_name='fact_cad_wgrkgjd',
            name='parse_time',
            field=models.DateTimeField(db_column='爬取时间'),
        ),
        migrations.AlterField(
            model_name='fact_cal_cbcyd',
            name='parse_time',
            field=models.DateTimeField(db_column='爬取时间'),
        ),
        migrations.AlterField(
            model_name='fact_cal_hscb',
            name='parse_time',
            field=models.DateTimeField(db_column='爬取时间'),
        ),
        migrations.AlterField(
            model_name='fact_pom_gd',
            name='parse_time',
            field=models.DateTimeField(db_column='爬取时间'),
        ),
        migrations.AlterField(
            model_name='fact_pom_scllsctl',
            name='parse_time',
            field=models.DateTimeField(db_column='爬取时间'),
        ),
        migrations.AlterField(
            model_name='fact_pom_wgtk',
            name='parse_time',
            field=models.DateTimeField(db_column='爬取时间'),
        ),
        migrations.AlterField(
            model_name='fact_pom_zjqd',
            name='parse_time',
            field=models.DateTimeField(db_column='爬取时间'),
        ),
        migrations.AlterField(
            model_name='fact_sca_clhygjd',
            name='parse_time',
            field=models.DateTimeField(db_column='爬取时间'),
        ),
        migrations.AlterField(
            model_name='fact_sca_wxsfyd',
            name='parse_time',
            field=models.DateTimeField(db_column='爬取时间'),
        ),
        migrations.AlterField(
            model_name='fact_sca_zyfyxsd',
            name='parse_time',
            field=models.DateTimeField(db_column='爬取时间'),
        ),
    ]
