# Generated by Django 3.2.6 on 2021-08-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0003_auto_20210817_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fact_act_hscb',
            fields=[
                ('md5_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('billno', models.CharField(db_column='单据编号', max_length=50)),
                ('typed', models.CharField(db_column='类型', max_length=50)),
                ('prod_pack', models.CharField(db_column='产品或组件', max_length=100)),
                ('unit_name', models.CharField(db_column='基本单位', max_length=50)),
                ('qty', models.FloatField(db_column='数量')),
                ('amount', models.FloatField(db_column='成本')),
                ('gd_id', models.CharField(db_column='生产工单', max_length=100)),
                ('cost_id', models.CharField(db_column='成本核算对象编码', max_length=100)),
                ('factory_id', models.CharField(db_column='工厂', max_length=50)),
                ('work_center', models.CharField(db_column='工作中心', max_length=50)),
                ('bill_type', models.CharField(db_column='单据类型', max_length=100)),
                ('business_date', models.DateTimeField(db_column='日期')),
                ('product_code', models.CharField(db_column='产品编码', max_length=100)),
                ('product_name', models.CharField(db_column='产品名称', max_length=100)),
                ('product_unit', models.CharField(db_column='产品单位', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='calu_ACT_HYCB',
        ),
        migrations.DeleteModel(
            name='dime_BD_materialgroup',
        ),
        migrations.DeleteModel(
            name='dime_Organization',
        ),
        migrations.DeleteModel(
            name='fact_Cad_WGRKGJD',
        ),
        migrations.DeleteModel(
            name='fact_Cal_CBCYD',
        ),
        migrations.DeleteModel(
            name='fact_Cal_HSCB',
        ),
        migrations.DeleteModel(
            name='fact_Pom_GD',
        ),
        migrations.DeleteModel(
            name='fact_Pom_SCLLSCTL',
        ),
        migrations.DeleteModel(
            name='fact_Pom_WGTK',
        ),
        migrations.DeleteModel(
            name='fact_Pom_ZJQD',
        ),
        migrations.DeleteModel(
            name='fact_Sca_CLHYGJD',
        ),
        migrations.DeleteModel(
            name='fact_Sca_WXSFYD',
        ),
        migrations.DeleteModel(
            name='fact_Sca_ZYFYXSD',
        ),
    ]
