# Generated by Django 3.2.6 on 2021-08-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0004_auto_20210818_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fact_act_hscb',
            name='amount',
            field=models.FloatField(db_column='成本', null=True),
        ),
        migrations.AlterField(
            model_name='fact_act_hscb',
            name='bill_type',
            field=models.CharField(db_column='单据类型', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fact_act_hscb',
            name='business_date',
            field=models.DateTimeField(db_column='日期', null=True),
        ),
        migrations.AlterField(
            model_name='fact_act_hscb',
            name='cost_id',
            field=models.CharField(db_column='成本核算对象编码', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fact_act_hscb',
            name='factory_id',
            field=models.CharField(db_column='工厂', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fact_act_hscb',
            name='gd_id',
            field=models.CharField(db_column='生产工单', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fact_act_hscb',
            name='prod_pack',
            field=models.CharField(db_column='产品或组件', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fact_act_hscb',
            name='product_code',
            field=models.CharField(db_column='产品编码', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fact_act_hscb',
            name='product_name',
            field=models.CharField(db_column='产品名称', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fact_act_hscb',
            name='product_unit',
            field=models.CharField(db_column='产品单位', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fact_act_hscb',
            name='qty',
            field=models.FloatField(db_column='数量', null=True),
        ),
        migrations.AlterField(
            model_name='fact_act_hscb',
            name='typed',
            field=models.CharField(db_column='类型', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fact_act_hscb',
            name='unit_name',
            field=models.CharField(db_column='基本单位', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fact_act_hscb',
            name='work_center',
            field=models.CharField(db_column='工作中心', max_length=50, null=True),
        ),
    ]
